# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_CAMERA_JACKPOT) += exynos7885-jackpotlte_kor_03.dtb \
	exynos7885-jackpotlte_kor_04.dtb \
	exynos7885-jackpotlte_kor_05.dtb \
	exynos7885-jackpotlte_kor_06.dtb \
	exynos7885-jackpotlte_kor_07.dtb

dtb-$(CONFIG_CAMERA_JACKPOT_JPN) += exynos7885-jackpotlte_jpn_dcm_00.dtb \
	exynos7885-jackpotlte_jpn_dcm_03.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
